/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docs: [],
  java: ['java/java', 'java/java-introduce', 'java/java-base'],
  interview: [
    {
      type: 'category',
      label: '常见面试题',
      link: {
        type: 'generated-index',
      },
      collapsible: true,
      collapsed: false,
      items: [
        'interview/interview-algorithm',
        'interview/interview-design',
        'interview/interview-base',
        'interview/interview-collection',
        'interview/interview-concurrency',
        'interview/interview-jvm',
        'interview/interview-microservice',
        'interview/interview-mysql',
        'interview/interview-redis',
        'interview/interview-mq',
        'interview/interview-spring',
        'interview/interview-mybatis',
        'interview/interview-other',
      ],
    },
  ],
}

module.exports = sidebars
