/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // 使用自动生成侧边栏
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  // docs侧边栏（暂无内容）
  docs: [],
  // Java侧边栏
  java: ['java/java', 'java/java-introduce', 'java/java-base', 'java/java-test'],
  // 面试侧边栏
  interview: [
    {
      type: 'category', // 类型为分类，展示的时候是可以下拉收缩的侧边栏项
      label: '常见面试题', // 侧边栏名称
      link: {
        type: 'generated-index', // 自动生成分类展示页内容
        title: '常见面试题', // 分类页标题
        description: '下面列举了一些常见的一些面试题专题。', // 分类页描述
        slug: '/interview', // 分类页地址
        keywords: ['面试'], // 关键字
        image: '/img/docusaurus.png', // 图片
      },
      collapsible: false, // 是否可伸缩
      collapsed: false, // 默认初始收起
      // 侧边栏子项
      items: [
        'interview/interview-algorithm',
        'interview/interview-design',
        'interview/interview-base',
        'interview/interview-collection',
        'interview/interview-concurrency',
        'interview/interview-jvm',
        'interview/interview-microservice',
        'interview/interview-mysql',
        'interview/interview-redis',
        'interview/interview-mq',
        'interview/interview-spring',
        'interview/interview-mybatis',
        'interview/interview-other',
      ],
    },
  ],
}

module.exports = sidebars
